name: Fetch Static Secrets example
'on': push
jobs:
  fetch_secrets:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch static secrets from Akeyless
        uses: akeylessio/github-action@v2
        id: fetch-secrets
        with:
          access-id: '${{ secrets.ACCESS_ID }}'
          access-type: jwt
          protection-key: '${{ secrets.AKEYLESS_PROTECTION_KEY }}'
          static-secrets: |
            - name: "/github_actions/demo_static_secret"
              output-name: "my_first_secret"
          gateway-url: "https://csm.thalescryptolabs.com/akeyless-api/"    
      - name: Use Akeyless secret
        run: |
            echo "Step Outputs"
            echo "my_first_secret: ${{ steps.fetch-secrets.outputs.my_first_secret }}" >> secrets.txt
            
            echo "Environment Variables"
            echo "my_first_secret: ${{ env.my_first_secret }}" >> secrets.txt
