name: Fetch Static Secrets example
'on': push
jobs:
  fetch_secrets:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch static secrets from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.0.1
        id: fetch-secrets
        with:
          access-id: '${{ secrets.ACCESS_ID }}'
          access-type: jwt
          static-secrets: |
            - name: "/github_actions/demo_static_secret"
              output-name: "fetched secret"
              key: "imp"
      - name: Use Akeyless secret
        run: >
          echo "Step Outputs"

          echo "fetched secret: ${{ steps.fetch-secrets.outputs.fetched secret
          }}" >> secrets.txt

          
          echo "Environment Variables"

          echo "fetched secret: ${{ env.fetched secret }}" >> secrets.txt

         
